import { Card, CardSuit, CardValue, Rank } from '@/types'

export const CardValueToBigInt = new Map<CardValue, bigint>([
  [CardValue.Two, BigInt(2)],
  [CardValue.Three, BigInt(3)],
  [CardValue.Four, BigInt(4)],
  [CardValue.Five, BigInt(5)],
  [CardValue.Six, BigInt(6)],
  [CardValue.Seven, BigInt(7)],
  [CardValue.Eight, BigInt(8)],
  [CardValue.Nine, BigInt(9)],
  [CardValue.Ten, BigInt(10)],
  [CardValue.Jack, BigInt(11)],
  [CardValue.King, BigInt(12)],
  [CardValue.Queen, BigInt(13)],
  [CardValue.Ace, BigInt(14)]
])

export const deck: Card[] = [
  { value: CardValue.Two, suit: CardSuit.Spade },
  { value: CardValue.Two, suit: CardSuit.Club },
  { value: CardValue.Two, suit: CardSuit.Diamond },
  { value: CardValue.Two, suit: CardSuit.Heart },
  { value: CardValue.Three, suit: CardSuit.Spade },
  { value: CardValue.Three, suit: CardSuit.Club },
  { value: CardValue.Three, suit: CardSuit.Diamond },
  { value: CardValue.Three, suit: CardSuit.Heart },
  { value: CardValue.Four, suit: CardSuit.Spade },
  { value: CardValue.Four, suit: CardSuit.Club },
  { value: CardValue.Four, suit: CardSuit.Diamond },
  { value: CardValue.Four, suit: CardSuit.Heart },
  { value: CardValue.Five, suit: CardSuit.Spade },
  { value: CardValue.Five, suit: CardSuit.Club },
  { value: CardValue.Five, suit: CardSuit.Diamond },
  { value: CardValue.Five, suit: CardSuit.Heart },
  { value: CardValue.Six, suit: CardSuit.Spade },
  { value: CardValue.Six, suit: CardSuit.Club },
  { value: CardValue.Six, suit: CardSuit.Diamond },
  { value: CardValue.Six, suit: CardSuit.Heart },
  { value: CardValue.Seven, suit: CardSuit.Spade },
  { value: CardValue.Seven, suit: CardSuit.Club },
  { value: CardValue.Seven, suit: CardSuit.Diamond },
  { value: CardValue.Seven, suit: CardSuit.Heart },
  { value: CardValue.Eight, suit: CardSuit.Spade },
  { value: CardValue.Eight, suit: CardSuit.Club },
  { value: CardValue.Eight, suit: CardSuit.Diamond },
  { value: CardValue.Eight, suit: CardSuit.Heart },
  { value: CardValue.Nine, suit: CardSuit.Spade },
  { value: CardValue.Nine, suit: CardSuit.Club },
  { value: CardValue.Nine, suit: CardSuit.Diamond },
  { value: CardValue.Nine, suit: CardSuit.Heart },
  { value: CardValue.Ten, suit: CardSuit.Spade },
  { value: CardValue.Ten, suit: CardSuit.Club },
  { value: CardValue.Ten, suit: CardSuit.Diamond },
  { value: CardValue.Ten, suit: CardSuit.Heart },
  { value: CardValue.Jack, suit: CardSuit.Spade },
  { value: CardValue.Jack, suit: CardSuit.Club },
  { value: CardValue.Jack, suit: CardSuit.Diamond },
  { value: CardValue.Jack, suit: CardSuit.Heart },
  { value: CardValue.Queen, suit: CardSuit.Spade },
  { value: CardValue.Queen, suit: CardSuit.Club },
  { value: CardValue.Queen, suit: CardSuit.Diamond },
  { value: CardValue.Queen, suit: CardSuit.Heart },
  { value: CardValue.King, suit: CardSuit.Spade },
  { value: CardValue.King, suit: CardSuit.Club },
  { value: CardValue.King, suit: CardSuit.Diamond },
  { value: CardValue.King, suit: CardSuit.Heart },
  { value: CardValue.Ace, suit: CardSuit.Spade },
  { value: CardValue.Ace, suit: CardSuit.Club },
  { value: CardValue.Ace, suit: CardSuit.Diamond },
  { value: CardValue.Ace, suit: CardSuit.Heart }
]

export const CardImage: Map<string, string> = new Map<string, string>([
  [JSON.stringify({ value: CardValue.Two, suit: CardSuit.Spade }), '/assets/cards/2_of_spades.svg'],
  [JSON.stringify({ value: CardValue.Two, suit: CardSuit.Club }), '/assets/cards/2_of_clubs.svg'],
  [JSON.stringify({ value: CardValue.Two, suit: CardSuit.Diamond }), '/assets/cards/2_of_diamonds.svg'],
  [JSON.stringify({ value: CardValue.Two, suit: CardSuit.Heart }), '/assets/cards/2_of_hearts.svg'],
  [JSON.stringify({ value: CardValue.Three, suit: CardSuit.Spade }), '/assets/cards/3_of_spades.svg'],
  [JSON.stringify({ value: CardValue.Three, suit: CardSuit.Club }), '/assets/cards/3_of_clubs.svg'],
  [JSON.stringify({ value: CardValue.Three, suit: CardSuit.Diamond }), '/assets/cards/3_of_diamonds.svg'],
  [JSON.stringify({ value: CardValue.Three, suit: CardSuit.Heart }), '/assets/cards/3_of_hearts.svg'],
  [JSON.stringify({ value: CardValue.Four, suit: CardSuit.Spade }), '/assets/cards/4_of_spades.svg'],
  [JSON.stringify({ value: CardValue.Four, suit: CardSuit.Club }), '/assets/cards/4_of_clubs.svg'],
  [JSON.stringify({ value: CardValue.Four, suit: CardSuit.Diamond }), '/assets/cards/4_of_diamonds.svg'],
  [JSON.stringify({ value: CardValue.Four, suit: CardSuit.Heart }), '/assets/cards/4_of_hearts.svg'],
  [JSON.stringify({ value: CardValue.Five, suit: CardSuit.Spade }), '/assets/cards/5_of_spades.svg'],
  [JSON.stringify({ value: CardValue.Five, suit: CardSuit.Club }), '/assets/cards/5_of_clubs.svg'],
  [JSON.stringify({ value: CardValue.Five, suit: CardSuit.Diamond }), '/assets/cards/5_of_diamonds.svg'],
  [JSON.stringify({ value: CardValue.Five, suit: CardSuit.Heart }), '/assets/cards/5_of_hearts.svg'],
  [JSON.stringify({ value: CardValue.Six, suit: CardSuit.Spade }), '/assets/cards/6_of_spades.svg'],
  [JSON.stringify({ value: CardValue.Six, suit: CardSuit.Club }), '/assets/cards/6_of_clubs.svg'],
  [JSON.stringify({ value: CardValue.Six, suit: CardSuit.Diamond }), '/assets/cards/6_of_diamonds.svg'],
  [JSON.stringify({ value: CardValue.Six, suit: CardSuit.Heart }), '/assets/cards/6_of_hearts.svg'],
  [JSON.stringify({ value: CardValue.Seven, suit: CardSuit.Spade }), '/assets/cards/7_of_spades.svg'],
  [JSON.stringify({ value: CardValue.Seven, suit: CardSuit.Club }), '/assets/cards/7_of_clubs.svg'],
  [JSON.stringify({ value: CardValue.Seven, suit: CardSuit.Diamond }), '/assets/cards/7_of_diamonds.svg'],
  [JSON.stringify({ value: CardValue.Seven, suit: CardSuit.Heart }), '/assets/cards/7_of_hearts.svg'],
  [JSON.stringify({ value: CardValue.Eight, suit: CardSuit.Spade }), '/assets/cards/8_of_spades.svg'],
  [JSON.stringify({ value: CardValue.Eight, suit: CardSuit.Club }), '/assets/cards/8_of_clubs.svg'],
  [JSON.stringify({ value: CardValue.Eight, suit: CardSuit.Diamond }), '/assets/cards/8_of_diamonds.svg'],
  [JSON.stringify({ value: CardValue.Eight, suit: CardSuit.Heart }), '/assets/cards/8_of_hearts.svg'],
  [JSON.stringify({ value: CardValue.Nine, suit: CardSuit.Spade }), '/assets/cards/9_of_spades.svg'],
  [JSON.stringify({ value: CardValue.Nine, suit: CardSuit.Club }), '/assets/cards/9_of_clubs.svg'],
  [JSON.stringify({ value: CardValue.Nine, suit: CardSuit.Diamond }), '/assets/cards/9_of_diamonds.svg'],
  [JSON.stringify({ value: CardValue.Nine, suit: CardSuit.Heart }), '/assets/cards/9_of_hearts.svg'],
  [JSON.stringify({ value: CardValue.Ten, suit: CardSuit.Spade }), '/assets/cards/10_of_spades.svg'],
  [JSON.stringify({ value: CardValue.Ten, suit: CardSuit.Club }), '/assets/cards/10_of_clubs.svg'],
  [JSON.stringify({ value: CardValue.Ten, suit: CardSuit.Diamond }), '/assets/cards/10_of_diamonds.svg'],
  [JSON.stringify({ value: CardValue.Ten, suit: CardSuit.Heart }), '/assets/cards/10_of_hearts.svg'],
  [JSON.stringify({ value: CardValue.Jack, suit: CardSuit.Spade }), '/assets/cards/jack_of_spades.svg'],
  [JSON.stringify({ value: CardValue.Jack, suit: CardSuit.Club }), '/assets/cards/jack_of_clubs.svg'],
  [JSON.stringify({ value: CardValue.Jack, suit: CardSuit.Diamond }), '/assets/cards/jack_of_diamonds.svg'],
  [JSON.stringify({ value: CardValue.Jack, suit: CardSuit.Heart }), '/assets/cards/jack_of_hearts.svg'],
  [JSON.stringify({ value: CardValue.Queen, suit: CardSuit.Spade }), '/assets/cards/queen_of_spades.svg'],
  [JSON.stringify({ value: CardValue.Queen, suit: CardSuit.Club }), '/assets/cards/queen_of_clubs.svg'],
  [JSON.stringify({ value: CardValue.Queen, suit: CardSuit.Diamond }), '/assets/cards/queen_of_diamonds.svg'],
  [JSON.stringify({ value: CardValue.Queen, suit: CardSuit.Heart }), '/assets/cards/queen_of_hearts.svg'],
  [JSON.stringify({ value: CardValue.King, suit: CardSuit.Spade }), '/assets/cards/king_of_spades.svg'],
  [JSON.stringify({ value: CardValue.King, suit: CardSuit.Club }), '/assets/cards/king_of_clubs.svg'],
  [JSON.stringify({ value: CardValue.King, suit: CardSuit.Diamond }), '/assets/cards/king_of_diamonds.svg'],
  [JSON.stringify({ value: CardValue.King, suit: CardSuit.Heart }), '/assets/cards/king_of_hearts.svg'],
  [JSON.stringify({ value: CardValue.Ace, suit: CardSuit.Spade }), '/assets/cards/ace_of_spades.svg'],
  [JSON.stringify({ value: CardValue.Ace, suit: CardSuit.Club }), '/assets/cards/ace_of_clubs.svg'],
  [JSON.stringify({ value: CardValue.Ace, suit: CardSuit.Diamond }), '/assets/cards/ace_of_diamonds.svg'],
  [JSON.stringify({ value: CardValue.Ace, suit: CardSuit.Heart }), '/assets/cards/ace_of_hearts.svg']
])

export const SmallBlindValue = 1
export const BigBlindValue = 2
export const BalanceValue = 1000

// @ts-ignore
type TCardRank = { [key: any]: string }

export const CardRank: Map<Rank, string> = new Map([
  [Rank.HighCard, 'Mậu Thầu'],
  [Rank.OnePair, '1 Đôi'],
  [Rank.TwoPair, '2 Đôi'],
  [Rank.ThreeOfKind, 'Sám'],
  [Rank.Straight, 'Sảnh'],
  [Rank.Flush, 'Thùng'],
  [Rank.FullHouse, 'Cù Lũ'],
  [Rank.FourOfKind, 'Tứ Quý'],
  [Rank.StraightFlush, 'Sảnh Thùng'],
  [Rank.RoyalFlush, 'Thùng Phá Sảnh']
])
